# Site settings
title: Semente
description: > # this means to ignore newlines until "baseurl:"
    Uma escola Waldorf
url: "http://sementewaldorf.com.br"
baseurl: ""
permalink: ":title"

exclude:
  - node_modules
  - bower.json
  - CHANGELOG.md
  - gulpfile.js
  - package.json
  - README.md
  - GEMFILE

# Plugins
gems: ["jekyll-sitemap", "jekyll-paginate"]

highlighter: rouge

markdown: rdiscount
markdown: kramdown