# Site settings
title: Semente
description: > # this means to ignore newlines until "baseurl:"
    Uma escola Waldorf
url: "http://sementewaldorf.com.br"
baseurl: ""
permalink: "posts/:title"
highlighter: rouge
markdown: rdiscount
markdown: kramdown